WITH RECURSIVE wood AS (
SELECT ID, NAME, CHIEF_ID, 1 AS depth
FROM EMPLOYEE
WHERE CHIEF_ID IS NULL
UNION ALL
SELECT e.ID, e.NAME, e.CHIEF_ID, c.depth + 1
FROM EMPLOYEE e
JOIN wood c ON e.CHIEF_ID = c.ID
)
SELECT MAX(depth) AS max_chain_length
FROM wood;