SELECT d.NAME AS DEPARTAMENT_NAME, SUM(e.SALARY) AS TOTAL_SALARY
FROM EMPLOYEE e
JOIN departament d ON e.DEPARTAMENT_ID = d.ID
GROUP BY e.DEPARTAMENT_ID, d.NAME
HAVING SUM(e.SALARY) = (
  SELECT MAX(sum_salary)
  FROM (
    SELECT SUM(SALARY) sum_salary
    FROM EMPLOYEE
    GROUP BY DEPARTAMENT_ID
  ) sum
)
